import { IconFileDownload } from "@tabler/icons-react";

export const invoiceData = [
  {
    id: 714831,
    name: "Emily Jackson",
    title: "Marketing Manager",
    company: "Global Industries",
    location: "New York, USA",
    date: "8/16/22",
    file: <IconFileDownload />,
    status: "Paid",
  },
  {
    id: 437987,
    name: "John Smith",
    title: "Software Engineer",
    company: "Tech Innovations",
    location: "San Francisco, USA",
    date: "10/10/22",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 651288,
    name: "Maria Rodriguez",
    title: "Sales Associate",
    company: "Ace Corporation",
    location: "Miami, USA",
    date: "5/15/22",
    file: <IconFileDownload />,
    status: "Paid",
  },
  {
    id: 942106,
    name: "David Lee",
    title: "Product Designer",
    company: "Artisan Creations",
    location: "London, UK",
    date: "12/1/22",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 117539,
    name: "Sarah Brown",
    title: "HR Director",
    company: "Peak Performance",
    location: "Toronto, Canada",
    date: "3/20/22",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 873925,
    name: "Alex Wong",
    title: "Project Manager",
    company: "Innovative Solutions",
    location: "Singapore",
    date: "9/5/22",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 394817,
    name: "Sophie Kim",
    title: "Operations Manager",
    company: "Strategic Ventures",
    location: "Seoul, South Korea",
    date: "7/1/22",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 657120,
    name: "James Johnson",
    title: "Accountant",
    company: "Precision Accounting",
    location: "Melbourne, Australia",
    date: "11/30/2022",
    file: <IconFileDownload />,
    status: "Pending",
  },
  {
    id: 528472,
    name: "Julia Chen",
    title: "Marketing Coordinator",
    company: "Digital Dream",
    location: "Shanghai, China",
    date: "6/15/22",
    file: <IconFileDownload />,
    status: "Paid",
  },
  {
    id: 169534,
    name: "Mohammed Ahmed",
    title: "IT Specialist",
    company: "TechWave",
    location: "Dubai, UAE",
    date: "2/10/22",
    file: <IconFileDownload />,
    status: "Paid",
  },
];
